service: medical-appointments-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: appointments-table-dev
    SNS_TOPIC_ARN: arn:aws:sns:${aws:region}:${aws:accountId}:appointments-topic
    SQS_PE_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/SQS_PE
    SQS_CL_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/SQS_CL
    EVENT_BUS_NAME: appointments-bus
  iam:
    role:
      statements:
        # DynamoDB permissions
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
          Resource: 
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/appointments-table-dev"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/appointments-table-dev/index/*"
        # SNS permissions
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: "arn:aws:sns:${aws:region}:${aws:accountId}:appointments-topic"
        # SQS permissions
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - "arn:aws:sqs:${aws:region}:${aws:accountId}:SQS_PE"
            - "arn:aws:sqs:${aws:region}:${aws:accountId}:SQS_CL"
            - "arn:aws:sqs:${aws:region}:${aws:accountId}:SQS_Confirmation"
        # EventBridge permissions
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "arn:aws:events:${aws:region}:${aws:accountId}:event-bus/appointments-bus"

plugins:
  - serverless-auto-swagger
  - serverless-esbuild

custom:
  autoswagger:
    title: 'Medical Appointments API'
    apiType: 'httpApi'
    generateSwaggerOnDeploy: true
    typefiles: ['./src/domain/entities/Appointment.ts']
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10

functions:
  appointment:
    handler: src/functions/appointment/handler.main
    events:
      - httpApi:
          method: POST
          path: /appointments
          bodyType: AppointmentRequest
          responseData:
            201:
              description: 'Cita creada exitosamente'
              bodyType: Appointment
      - httpApi:
          method: GET
          path: /appointments/{insuredId}
      - sqs:
          arn: arn:aws:sqs:${aws:region}:${aws:accountId}:SQS_Confirmation
          batchSize: 10

  appointment_pe:
    handler: src/functions/appointment_pe/handler.main
    events:
      - sqs:
          arn: arn:aws:sqs:${aws:region}:${aws:accountId}:SQS_PE
          batchSize: 10

  appointment_cl:
    handler: src/functions/appointment_cl/handler.main
    events:
      - sqs:
          arn: arn:aws:sqs:${aws:region}:${aws:accountId}:SQS_CL
          batchSize: 10
